import { Component, OnDestroy, OnInit } from "@angular/core";
import { CommonModule } from "@angular/common";
import { Subject } from 'rxjs';
import { RouterLink, RouterModule } from '@angular/router';

@Component({
  selector: "app-fragment-bar",
  templateUrl: "./fragment-bar.component.html",
  styleUrls: ["./fragment-bar.component.scss"],
  standalone: true,
  imports: [CommonModule, RouterModule, RouterLink]
})
export class FragmentBarComponent implements OnDestroy{
  /**
   * Component destroyed stream
   */
  componentDestroyed$: Subject<void> = new Subject<void>();
  f_custom1 = '?utm_source=hola#?t=eyJhbGciOiJSUzI1NiIsImN0eSI6InRoZWFuby10b2tlbitqc29uIiwia2lkIjoiM2E6OGM6YmY6ZTc6ZTk6NWI6Y2I6YzU6NDg6M2I6M2M6ZmY6OTY6OTg6YjQ6NzMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJ6LW5rLmltb2xrby5uZXQiLCJhdWQiOlsiQHRoZWFuby5pbW9sa28ubmV0Il0sImV4cCI6MTcxODk4MTg4NSwibmJmIjoxNzE4ODk1NDg1LCJpYXQiOjE3MTg4OTU0ODUsIm93biI6ImJlYXRyaXoiLCJmaWQiOlsiNjY3MzJhNjQ5OTMyY2RiZjU0MmMwYWVhIl0sImFpZCI6WyI2NjZiMjFhOTkyOWRkOGFjNzZiMWNjODIiXSwiZGlkIjpbIjJocGhidHF1bmtvSXpuTGc0RENseERrZjVxWiJdLCJjdHAiOiJSRUNBUFRDSEFfVjMiLCJjc2siOiI2TGQzMk1NVUFBQUFBS09DYTVUTkpGTUJKenE2RW50SWxFNEs2WUNoIn0.AKJuiIfeVujsHcNKBCdGIJuJzz9Z79MKVswJSu3yhGwFAuLoqfyLD9moCfqQjp7aB8GanXKAGtUqJQLQe_pj1laEAPXZ-3I5TW0ScEyPS8pHZKzfiXEMKwiAW1QnmwHTHv0gWfPfWcetKd4zyB3qEZY0spTT6vmmGMklEq4TXjwfwDf1eEFilGOxAuyjfA_FMbUihV3w-KvtjCuNrQDwELvofbF-Tx9FuAFqHP7limZN9dboJT26tNYz9ocaeHoB6jbLS5ONn1Q3SEVQdEScv64q8hBwckSgpLNhJSBHklfAAbLdwcFV0d34u_dTYP6Xrfr9tuaZi-Oxq4AhpvIovqWJX1PnL6IhlU-zOxuenwVdfTrzB9VecsoHzQjchIaCo5SGL1N0Bo1upu-AzGGXbRcfGHrOie1pAcrEgAtiLPvDn3zpuOj3B06CeO0LCvor1ilh7LqgBzXpHQ5-jlLT7zZQMjQ48teTBDWPp-4IGt52sEcnC2mx2zWF2KQGy969Tt9rjvJm6isdEVb8Vs2spiSU3WyAJYLtvM-pmJWxJ-jZjk4k3ILO3zcc-tcyj1gTuz3z8cCiEikdH9kG3YF1_pzP6WmKsN-2jKhEL8XREPGncWNtDNQxrVKQWcDVoBdPjwczCDFKiT_GlsBGdEtJaQDGUYleZcH9im-wYdFaVRM&prefill=e30';
  f_custom2 = '?t=eyJhbGciOiJSUzI1NiIsImN0eSI6InRoZWFuby10b2tlbitqc29uIiwia2lkIjoiM2E6OGM6YmY6ZTc6ZTk6NWI6Y2I6YzU6NDg6M2I6M2M6ZmY6OTY6OTg6YjQ6NzMiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJ6LW5rLmltb2xrby5uZXQiLCJhdWQiOlsiQHRoZWFuby5pbW9sa28ubmV0Il0sImV4cCI6MTcxODk4MTg4NSwibmJmIjoxNzE4ODk1NDg1LCJpYXQiOjE3MTg4OTU0ODUsIm93biI6ImJlYXRyaXoiLCJmaWQiOlsiNjY3MzJhNjQ5OTMyY2RiZjU0MmMwYWVhIl0sImFpZCI6WyI2NjZiMjFhOTkyOWRkOGFjNzZiMWNjODIiXSwiZGlkIjpbIjJocGhidHF1bmtvSXpuTGc0RENseERrZjVxWiJdLCJjdHAiOiJSRUNBUFRDSEFfVjMiLCJjc2siOiI2TGQzMk1NVUFBQUFBS09DYTVUTkpGTUJKenE2RW50SWxFNEs2WUNoIn0.AKJuiIfeVujsHcNKBCdGIJuJzz9Z79MKVswJSu3yhGwFAuLoqfyLD9moCfqQjp7aB8GanXKAGtUqJQLQe_pj1laEAPXZ-3I5TW0ScEyPS8pHZKzfiXEMKwiAW1QnmwHTHv0gWfPfWcetKd4zyB3qEZY0spTT6vmmGMklEq4TXjwfwDf1eEFilGOxAuyjfA_FMbUihV3w-KvtjCuNrQDwELvofbF-Tx9FuAFqHP7limZN9dboJT26tNYz9ocaeHoB6jbLS5ONn1Q3SEVQdEScv64q8hBwckSgpLNhJSBHklfAAbLdwcFV0d34u_dTYP6Xrfr9tuaZi-Oxq4AhpvIovqWJX1PnL6IhlU-zOxuenwVdfTrzB9VecsoHzQjchIaCo5SGL1N0Bo1upu-AzGGXbRcfGHrOie1pAcrEgAtiLPvDn3zpuOj3B06CeO0LCvor1ilh7LqgBzXpHQ5-jlLT7zZQMjQ48teTBDWPp-4IGt52sEcnC2mx2zWF2KQGy969Tt9rjvJm6isdEVb8Vs2spiSU3WyAJYLtvM-pmJWxJ-jZjk4k3ILO3zcc-tcyj1gTuz3z8cCiEikdH9kG3YF1_pzP6WmKsN-2jKhEL8XREPGncWNtDNQxrVKQWcDVoBdPjwczCDFKiT_GlsBGdEtJaQDGUYleZcH9im-wYdFaVRM&prefill=e30';
  /**
   * Destructor del componente
   */
  ngOnDestroy() {
    this.componentDestroyed$.next();
    this.componentDestroyed$.complete();
  }
}